useAverage: true
averageLength: 10
interval: 40
log:
    interval: 150
    enable: true
    useLogsFolder: false
    logPlayersOnline: true
Notifications:
    Lag:
        Enabled: true
        Threshold: 17
        CheckInterval: 5
        ConsoleCommand: lag
    Memory:
        Enabled: true
        Threshold: 25
        CheckInterval: 10
        ConsoleCommand: mem